# Generated by Django 3.0.6 on 2020-05-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='rates',
        ),
        migrations.AddField(
            model_name='rate',
            name='rates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rates.Rates'),
            preserve_default=False,
        ),
    ]
