# Generated by Django 3.0.6 on 2020-05-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20200505_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='rates', to='rates.Rates', verbose_name='rates'),
        ),
    ]
